// <auto-generated />
using System;
using KnifeStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KnifeStore.Migrations.BasketDb
{
    [DbContext(typeof(BasketDbContext))]
    partial class BasketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnifeStore.Models.Basket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("KnifeStore.Models.Knife", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasketID");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int?>("ManufacturerID");

                    b.Property<string>("Model");

                    b.Property<decimal>("Price");

                    b.Property<string>("SKU");

                    b.Property<int>("Style");

                    b.HasKey("ID");

                    b.HasIndex("BasketID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("Knife");
                });

            modelBuilder.Entity("KnifeStore.Models.KnifeManufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("KnifeManufacturer");
                });

            modelBuilder.Entity("KnifeStore.Models.Knife", b =>
                {
                    b.HasOne("KnifeStore.Models.Basket")
                        .WithMany("Items")
                        .HasForeignKey("BasketID");

                    b.HasOne("KnifeStore.Models.KnifeManufacturer", "Manufacturer")
                        .WithMany("Knives")
                        .HasForeignKey("ManufacturerID");
                });
#pragma warning restore 612, 618
        }
    }
}
